name: Hello World
 
 
on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 
 
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
 
    steps:
    - name: Print Hello World
      run: echo "Hello, World!"

    - name: Build the Docker image
      working-directory: ./ArtistAPI
      run: docker build -t amardeep/newimage 