name: Hello World
 
 
on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 
 
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
 
    steps:
    - name: Print Hello World
      run: echo "Hello, World!"

    - uses: actions/checkout@v4
    - name: Build and upload Docker image
      run: | 
        docker build ./ArtistAPI -t amardeep/newimage
        docker tag amardeep/newimage ${{secrets.REGISTRY}}/amardeep/newimage:latest
        docker login ${{secrets.REGISTRY}} -u ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}} 
        docker push ${{secrets.REGISTRY}}/amardeep/newimage:latest