name: docker build

on:
  push:
    branches: 
    - main
    pull_request:
      branches:
      - main
    

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps: 
    - name: checkout from repo
    uses: actions/checkout@v2

    -name: Print Hello World
    uses: echo "Hello, World!"        